import "../../styles/globals.css";
import Link from "next/link";
import Head from "next/head";

// font
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flask website CRUD",
  description: "Generated by create next app & Flask",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang=""">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

function MyApp({ Component, pageProps }) {
  return (
    <html lang="en">
      <head>
        {/* 這裡可以加入你的網站的全局 <head> 內容，例如 meta 標籤、標題等 */}
      </head>
      <body>
        <header>
          {/* 這裡可以加入你的網站的全局 header 內容 */}
          {/* 以 Next.js 的 Link 進行導航 */}
          <Link href="/">首頁</Link>
          <Link href="/about">關於</Link>
          {/* ... 其他導航項目 */}
        </header>

        {/* 這是你每一頁的內容 */}
        <Component {...pageProps} />

        <footer>{/* 這裡可以加入你的網站的全局 footer 內容 */}</footer>
      </body>
    </html>
  );
}

export default MyApp;

// function Layout({
//     children,
//     title = "Default Title",
//     username,
//     integer,
//     message,
//   }) {
//     return (
//       <div>
//         <Head>
//           <title>{title}</title>
//           {/* ...其他meta tags... */}
//           <link rel="icon" href="/favicon.ico" />
//           {/* ...其他styles和scripts... */}
//         </Head>
//         <header>
//           <div className="jumbotron text-center text-white">
//             <h1 className="home">
//               <a href="/">
//                 Welcome to
//                 {username
//                   ? `${username}'s`
//                   : integer
//                   ? `square ${integer}`
//                   : message
//                   ? `error ${message}`
//                   : "my"}{" "}
//                 world!
//               </a>
//             </h1>
//           </div>
//         </header>
//         {children}
//         {/* ...其他元素，如 loading div 和 footer... */}
//       </div>
//     );
//   }
